on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.rc[0-9]+'

jobs:
  testjob:
    name: some job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
        ref: ${GITHUB_REF}
        fetch-depth: 0
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: rebase canary on tag
        run: git rebase ${} canary
      - name: push canary
        run: git push origin canary

